name: Deploy Frontend to Vercel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Jest Unit tests
      - name: Run Jest Unit Tests
        run: npm run test

      # Step 5: Run Cypress E2E tests
      - name: Run Cypress E2E Tests
        run: npx cypress run

  deploy:
    needs: test # This makes sure the 'deploy' job runs only if 'test' succeeds
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment (same as in the test job)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Deploy to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Token stored in GitHub Secrets
        run: vercel --prod --token $VERCEL_TOKEN # Deploy to Vercel Production
